export const menuData = [
  {
    id: Math.floor(Math.random() * 1000),
    name: "Burger",
    price: 150,
    img: "/assets/items/burger.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Pizza",
    price: 300,
    img: "/assets/items/pizza.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Pasta",
    price: 250,
    img: "/assets/items/pasta.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Salad",
    price: 180,
    img: "/assets/items/salad.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Ice-cream Vadapav",
    price: 150,
    img: "/assets/items/icecreamVadapav.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Chicken Biryani",
    price: 220,
    img: "/assets/items/chickenBiryani.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Paneer Tikka",
    price: 180,
    img: "/assets/items/paneerTikka.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Butter Chicken",
    price: 280,
    img: "/assets/items/butterChicken.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Masala Dosa",
    price: 120,
    img: "/assets/items/masalaDosa.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Chole Bhature",
    price: 150,
    img: "/assets/items/choleBhature.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Samosa",
    price: 20,
    img: "/assets/items/samosa.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Rajma Chawal",
    price: 180,
    img: "/assets/items/rajmaChawal.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Gulab Jamun",
    price: 60,
    img: "/assets/items/gulabJamun.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Aloo Paratha",
    price: 100,
    img: "/assets/items/alooParatha.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Dal Makhani",
    price: 150,
    img: "/assets/items/dalMakhani.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Rasgulla",
    price: 50,
    img: "/assets/items/rasgulla.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Palak Paneer",
    price: 180,
    img: "/assets/items/palakPaneer.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Tandoori Roti",
    price: 20,
    img: "/assets/items/tandooriRoti.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Mutton Curry",
    price: 350,
    img: "/assets/items/muttonCurry.jpg",
  },
  {
    id: Math.floor(Math.random() * 1000),
    name: "Fish Curry",
    price: 280,
    img: "/assets/items/fishCurry.jpg",
  },
];
